name: Contracts

on:
  push:
    paths:
      - "contracts/**"
  pull_request:
    paths:
      - "contracts/**"

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
      - run: cargo test --workspace --all
      - run: cargo build --workspace --release --target wasm32-unknown-unknown
